import { invoke } from '@tauri-apps/api/core'
import { useReferencesStore } from '../stores/references'

const lastWrittenBibContent = new Map()

/**
 * Auto-generates a `references.bib` file from the reference library.
 * Called before each LaTeX compilation to ensure citations are up to date.
 *
 * @param {string} texPath - Path to the .tex file being compiled
 * @returns {string} Path to the generated .bib file
 */
export async function ensureBibFile(texPath) {
  const referencesStore = useReferencesStore()

  // Generate .bib in the same directory as the .tex file
  const dir = texPath.substring(0, texPath.lastIndexOf('/'))
  const bibPath = dir + '/references.bib'

  // Export all references as BibTeX
  const bibContent = referencesStore.exportBibTeX()

  if (!bibContent.trim()) {
    // No references — still write an empty file so \bibliography doesn't error
    const emptyContent = '% Auto-generated by Altals\n'
    if (lastWrittenBibContent.get(bibPath) !== emptyContent) {
      await invoke('write_file', { path: bibPath, content: emptyContent })
      lastWrittenBibContent.set(bibPath, emptyContent)
    }
    return bibPath
  }

  const header = '% Auto-generated by Altals from reference library\n% Do not edit manually - changes will be overwritten on next compile\n\n'
  const nextContent = header + bibContent + '\n'
  if (lastWrittenBibContent.get(bibPath) !== nextContent) {
    await invoke('write_file', { path: bibPath, content: nextContent })
    lastWrittenBibContent.set(bibPath, nextContent)
  }

  return bibPath
}
